language: java
addons:
    mariadb: '10.0'
before_install:
    - mysql -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'password';"
    - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;"
