language: java
addons:
    mariadb: '10.0'
before_install:
    - mysql -u root GymSystem < $TRAVIS_BUILD_DIR/java-web-project/db_schema/gym_system_schema.sql
    - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('password');"
